- type: worldgenConfig
  id: AfterlightDefault
  components:
    - type: WorldController
    - type: BiomeSelection
      biomes:
        - CitadelAsteroidsFallback
        - CitadelFailsafe
        - AfterlightAsteroidsStandard
    - type: ShipSpawning
      loadedSpawnArea: 8
