- type: worldgenConfig
  id: Default
  components:
    - type: WorldController
    - type: BiomeSelection
      biomes:
        - CitadelAsteroidsFallback
        - CitadelFailsafe
        - CitadelAsteroidsStandard
    - type: ShipSpawning
      loadedSpawnArea: 8
